apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8000  
  type: LoadBalancer
